experiment:
  name: act_lang_ABC_resume_smoke
  seed: 1000
  output_dir: /home/zengzixuan/cvprojects/lerobot/project/outputs/act_lang_ABC_resume_smoke
dataset:
  repo_id: local/calvin_lang_ABC
  root: /EXT_DISK/users/zengzixuan/processed-calvin/calvin_lang_ABC
  train_episodes: 0:16083
  val_episodes: 16083:17870
  use_imagenet_stats: true
  return_uint8: true
  video_backend: null
policy:
  type: act_lang
  device: cuda:0
  use_amp: false
  push_to_hub: false
  pretrained_backbone_weights: ResNet18_Weights.IMAGENET1K_V1
  n_obs_steps: 1
  chunk_size: 100
  n_action_steps: 100
  vision_backbone: resnet18
  dim_model: 512
  n_heads: 8
  dim_feedforward: 3200
  n_encoder_layers: 4
  n_decoder_layers: 1
  use_vae: true
  latent_dim: 32
  n_vae_encoder_layers: 4
  dropout: 0.1
  kl_weight: 10.0
  optimizer_lr: 1.0e-05
  optimizer_weight_decay: 0.0001
  optimizer_lr_backbone: 1.0e-05
  language_embedding_key: observation.language_embedding
  language_embedding_dim: 384
  language_fusion: conditioning_token
  language_projection_dim: 512
training:
  batch_size: 2
  steps: 100002
  resume_from: /EXT_DISK/users/zengzixuan/calvin_runs/act_lang_ABC/20260606_163515_act_lang_ABC_full_gpu1/checkpoint
  num_workers: 0
  log_freq: 1
  val_freq: 5000
  max_val_batches: 1
  grad_clip_norm: 10.0
  save_checkpoint: true
  save_freq: 0
  progress_bar: true
